



 # build/AppWhiskerGui --BLOW 2 --NO_CURVATURE 1 --TIME_STOP 2 --TIME_STEP 0.0001 --NUM_STEP_INT 100 --WHISKER_NAMES ALL --NUM_UNITS 2
  # ../build/AppWhiskerGui --BLOW 2 --NO_CURVATURE 0 --TIME_STOP 2 --WHISKER_NAMES ALL --NUM_UNITS 5
  ../build/AppWhiskerGui --BLOW 2 --NO_CURVATURE 0 --TIME_STOP 2 --TEST 1 --NUM_UNITS 5